import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import Column, Index, Text
from sqlmodel import Field, SQLModel


class Message(SQLModel, table=True):
    """A single chat message in a user's conversation.

    Roles:
      - 'user'        : message sent by the human
      - 'assistant'   : message generated by the AI
      - 'tool_call'   : AI requested a tool execution (content is JSON)
      - 'tool_result' : result of a tool execution (content is JSON)

    The composite index on (conversation_id, created_at) supports efficient
    ordered history loading.

    Ref: specs/003-ai-todo-chatbot/spec.md § Data Model
         specs/003-ai-todo-chatbot/plan.md § Data Model Changes
    """

    __tablename__ = "message"

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        nullable=False,
    )
    conversation_id: uuid.UUID = Field(
        foreign_key="conversation.id",
        nullable=False,
        # ON DELETE CASCADE defined in migration 002
    )
    # 'user' | 'assistant' | 'tool_call' | 'tool_result'
    role: str = Field(max_length=20, nullable=False)
    # Plain text for user/assistant; JSON string for tool_call/tool_result
    content: str = Field(sa_column=Column(Text, nullable=False))
    # Non-null only for tool_call and tool_result roles
    tool_name: Optional[str] = Field(default=None, max_length=100, nullable=True)
    created_at: datetime = Field(default_factory=datetime.utcnow, nullable=False)

    __table_args__ = (
        Index("idx_message_conversation_created", "conversation_id", "created_at"),
    )
